import os
import csv
import pandas as pd
from relogic_tg_excel_sync.sync_utils import sync_contacts

TRIAL_LIMIT = 20
TRIAL_WATERMARK = 'TRIAL VERSION - Generated by ReLogic'

def read_csv_contacts(csv_path):
    contacts = []
    with open(csv_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        # Lewati watermark di baris pertama jika ada
        if lines and lines[0].strip() == TRIAL_WATERMARK:
            lines = lines[1:]
        reader = csv.DictReader(lines)
        for row in reader:
            contacts.append(row)
    return contacts

def read_excel_contacts(excel_path):
    if not os.path.exists(excel_path):
        return []
    df = pd.read_excel(excel_path)
    return df.to_dict('records')

def write_excel_contacts(contacts, excel_path):
    df = pd.DataFrame(contacts)
    # Tambahkan watermark di baris pertama
    with pd.ExcelWriter(excel_path, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, startrow=1)
        ws = writer.sheets['Sheet1']
        ws['A1'] = TRIAL_WATERMARK

def main():
    print('*** INI ADALAH VERSI TRIAL. Hanya 20 kontak pertama yang disinkronkan. ***')
    base_dir = os.path.dirname(__file__)
    csv_path = os.path.join(base_dir, '../example_output/contacts.csv')
    excel_path = os.path.join(base_dir, '../example_output/contacts_synced.xlsx')
    tg_contacts = read_csv_contacts(csv_path)
    excel_contacts = read_excel_contacts(excel_path)
    synced_contacts = sync_contacts(tg_contacts, excel_contacts)
    synced_contacts = synced_contacts[:TRIAL_LIMIT]
    write_excel_contacts(synced_contacts, excel_path)
    print(f"Synced contacts written to {excel_path}")

if __name__ == '__main__':
    main()
